name: 'Automatic build'
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout source code
       uses: actions/checkout@main
      
      -name: Check Node version
       run: node -v
      
      -name: Install Dependencies
       run: npm install --frozen-lockfile

      -name: build
       run: npm run build